### ISSUE TITLE
Search functionality does report wrong number of occurrences

### ISSUE THREAD

**Issue by davidecenzato** [ddiazdom/LPG#16]
It seems like the ```./lpg search -F patterns.txt index_file``` command does report a total number of occurrences smaller than the correct one. I am reporting an example using the index constructed using the ```sample_file.txt``` file.
The  ```./lpg search sample_file.lpg_idx -p AAACT``` command gives the output:
```
Searching for patterns in the self-index
Index stats
  Index name:                                              sample_file.lpg_idx
  Index size:                                              965407 bytes 
  Orig. text len:                                          605265
  Number of bits in the index per input text symbol (bps): 12.7601
Searching for the patterns 
Locating 1 patterns 
Stats for the pattern collection
  Total elap. time (microsec): 3106
  Total occ: 585
  Time/occ (microsec): 5.3094
```
However, the correct number of occurrences of the AAACT pattern in the file is 949.

**Comment by ddiazdom** [comment]
Hi,

I think I fixed the problem. I accidentally introduced some errors in my last commit, but now is working properly again (I think). I will push the changes at some point before Monday.

**Comment by ddiazdom** [comment]
I updated the repo with the fixes. I checked the new version with  the file``einstein.en`` from the ``Pizza&Chili`` repetitive corpus, using patterns of length up to 500, and it is working. Let me know if you find any other error.
